### ISSUE TITLE
domain-search

### ISSUE THREAD

**Issue by asmodehn** [linuxhq/ansible-role-dhclient#1]
One setting I use (on ubuntu) is `supersede domain-search "my.domain.com", "domain.com";`

I think there is no option for this currently in this role ?

**Comment by tkimball83** [comment]
Apologies for not responding here.  I didn't get a notification for this and this role has been severely neglected.

I'm going to refactor this role shortly which will include support for this.  I'll follow up here when its completed.

**Comment by tkimball83** [comment]
This should be supported now with the new template, please confirm.

I'll keep this open for a few more days before closing.
