### ISSUE TITLE
prepend

### ISSUE THREAD

**Issue by asmodehn** [linuxhq/ansible-role-dhclient#2]
One setting I use (on ubuntu) is prepend domain-name-servers 192.168.3.3, 192.168.10.233;

I think there is currently no way to achieve this with this role ? ( I just had a look at the config template)

**Comment by asmodehn** [comment]
Not a big deal though. I currently can add google dns (8.8.8.8) at the end to get internet names.
I am not particularly attached to my Internet provider's DNS.

**Comment by tkimball83** [comment]
Apologies for not responding here.  I didn't get a notification for this and this role has been severely neglected.

I'm going to refactor this role shortly which will include support for this.  I'll follow up here when its completed.

**Comment by tkimball83** [comment]
This should be supported now with the new template, please confirm.

I'll keep this open for a few more days before closing.
